#pragma checksum "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "93D736B743EE9844A31A37C3B4B47E7C5250ABD415A2627BF3AC9C555C2BC3E0"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.OsTrader.Panels.Tab {
    
    
    /// <summary>
    /// BotTabIndexUi
    /// </summary>
    public partial class BotTabIndexUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 14 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabControlItem1;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostSecurity1;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonAccept;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSecurity1;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton ButtonSecurity2;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextboxUserFormula;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonClearAllSecurities;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelDepth;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxDepth;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxPercentNormalization;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabControlItem2;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeSettingsToRebuildFormula;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxRegime;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelRegime;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxDayOfWeekToRebuildIndex;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelDayOfWeekToRebuildIndex;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxHourInDayToRebuildIndex;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelHourInDayToRebuildIndex;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxWriteLogMessageOnRebuild;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTypeSettingsToRebuildFormula;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxIndexSortType;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelIndexSortType;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxIndexSecCount;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelIndexSecCount;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxIndexMultType;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelIndexMultType;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxDaysLookBackInBuilding;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelDaysLookBackInBuilding;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextboxUserFormulaSecondTab;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRebuildFormulaNow;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/ostrader/panels/tab/bottabindexui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TabControlItem1 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 2:
            this.HostSecurity1 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 3:
            this.ButtonAccept = ((System.Windows.Controls.Button)(target));
            
            #line 17 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
            this.ButtonAccept.Click += new System.Windows.RoutedEventHandler(this.ButtonAccept_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ButtonSecurity1 = ((System.Windows.Controls.Button)(target));
            
            #line 18 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
            this.ButtonSecurity1.Click += new System.Windows.RoutedEventHandler(this.ButtonAddSecurity_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ButtonSecurity2 = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 19 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
            this.ButtonSecurity2.Click += new System.Windows.RoutedEventHandler(this.RepeatButtonDeleteSecurity_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.TextboxUserFormula = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.ButtonClearAllSecurities = ((System.Windows.Controls.Button)(target));
            
            #line 21 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabIndexUi.xaml"
            this.ButtonClearAllSecurities.Click += new System.Windows.RoutedEventHandler(this.ButtonClearAllSecurities_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.LabelDepth = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.TextBoxDepth = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.CheckBoxPercentNormalization = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 11:
            this.TabControlItem2 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 12:
            this.LabelTimeSettingsToRebuildFormula = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.ComboBoxRegime = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 14:
            this.LabelRegime = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.ComboBoxDayOfWeekToRebuildIndex = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 16:
            this.LabelDayOfWeekToRebuildIndex = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.ComboBoxHourInDayToRebuildIndex = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 18:
            this.LabelHourInDayToRebuildIndex = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.CheckBoxWriteLogMessageOnRebuild = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 20:
            this.LabelTypeSettingsToRebuildFormula = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.ComboBoxIndexSortType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 22:
            this.LabelIndexSortType = ((System.Windows.Controls.Label)(target));
            return;
            case 23:
            this.ComboBoxIndexSecCount = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 24:
            this.LabelIndexSecCount = ((System.Windows.Controls.Label)(target));
            return;
            case 25:
            this.ComboBoxIndexMultType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 26:
            this.LabelIndexMultType = ((System.Windows.Controls.Label)(target));
            return;
            case 27:
            this.ComboBoxDaysLookBackInBuilding = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 28:
            this.LabelDaysLookBackInBuilding = ((System.Windows.Controls.Label)(target));
            return;
            case 29:
            this.TextboxUserFormulaSecondTab = ((System.Windows.Controls.TextBox)(target));
            return;
            case 30:
            this.ButtonRebuildFormulaNow = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

