#pragma checksum "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "7D3721CB23588C7E7C82BA998AE17C2E69F9E2D8ADE1B627EDA23C12B880ADA7"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using OsEngine.OsTrader.Panels.Tab;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.OsTrader.Panels.Tab {
    
    
    /// <summary>
    /// BotTabPolygonUi
    /// </summary>
    public partial class BotTabPolygonUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 9 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridPrime;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridTradePanel;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridSettings;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelStartSecutiySettings;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelComissionSettings;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxBaseCurrency;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelBaseCurrency;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxSeparatorToSecurities;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSeparator;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelComissionType;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxComissionType;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxComissionValue;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelComissionValue;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxCommisionIsSubstract;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxProfitToSignal;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelProfitToSignal;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxActionOnSignalType;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelActionOnSignalType;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridToTrade;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelExecutionSettings;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxDelayMls;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelInterval;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelDelay;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxDelayType;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonBuyLimit;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxLimitQtyStart;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelQtyStartLimit;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxLimitSlippage;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSlippageLimit;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelExecution;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelOrderPriceType;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxOrderPriceType;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostSequence;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridLog;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelLog;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostLog;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GreedChartPanel;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridSecurities;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostSec1;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostSec2;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSec1;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSec2;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridIndicators;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostSec3;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSec3;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonHideShowRightPanel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/ostrader/panels/tab/bottabpolygonui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.GridPrime = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.GridTradePanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.GridSettings = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.LabelStartSecutiySettings = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.LabelComissionSettings = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.TextBoxBaseCurrency = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.LabelBaseCurrency = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.TextBoxSeparatorToSecurities = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.LabelSeparator = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.LabelComissionType = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.ComboBoxComissionType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 12:
            this.TextBoxComissionValue = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.LabelComissionValue = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.CheckBoxCommisionIsSubstract = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 15:
            this.TextBoxProfitToSignal = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.LabelProfitToSignal = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.ComboBoxActionOnSignalType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 18:
            this.LabelActionOnSignalType = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.GridToTrade = ((System.Windows.Controls.Grid)(target));
            return;
            case 20:
            this.LabelExecutionSettings = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.TextBoxDelayMls = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.LabelInterval = ((System.Windows.Controls.Label)(target));
            return;
            case 23:
            this.LabelDelay = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.ComboBoxDelayType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 25:
            this.ButtonBuyLimit = ((System.Windows.Controls.Button)(target));
            return;
            case 26:
            this.TextBoxLimitQtyStart = ((System.Windows.Controls.TextBox)(target));
            return;
            case 27:
            this.LabelQtyStartLimit = ((System.Windows.Controls.Label)(target));
            return;
            case 28:
            this.TextBoxLimitSlippage = ((System.Windows.Controls.TextBox)(target));
            return;
            case 29:
            this.LabelSlippageLimit = ((System.Windows.Controls.Label)(target));
            return;
            case 30:
            this.LabelExecution = ((System.Windows.Controls.Label)(target));
            return;
            case 31:
            this.LabelOrderPriceType = ((System.Windows.Controls.Label)(target));
            return;
            case 32:
            this.ComboBoxOrderPriceType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 33:
            this.HostSequence = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 34:
            this.GridLog = ((System.Windows.Controls.Grid)(target));
            return;
            case 35:
            this.LabelLog = ((System.Windows.Controls.Label)(target));
            return;
            case 36:
            this.HostLog = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 37:
            this.GreedChartPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 38:
            this.GridSecurities = ((System.Windows.Controls.Grid)(target));
            return;
            case 39:
            this.HostSec1 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 40:
            this.HostSec2 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 41:
            this.ButtonSec1 = ((System.Windows.Controls.Button)(target));
            return;
            case 42:
            this.ButtonSec2 = ((System.Windows.Controls.Button)(target));
            return;
            case 43:
            this.GridIndicators = ((System.Windows.Controls.Grid)(target));
            return;
            case 44:
            this.HostSec3 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 45:
            this.ButtonSec3 = ((System.Windows.Controls.Button)(target));
            return;
            case 46:
            this.ButtonHideShowRightPanel = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

