#pragma checksum "..\..\..\OsData\OsDataSetDetailUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "C6C7EB964011F93C5BCA69CBDEE368377EFE9CDF236C4F6FF1E1D38743481896"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using OsEngine.OsData;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.OsData {
    
    
    /// <summary>
    /// OsDataSetDetailUi
    /// </summary>
    public partial class OsDataSetDetailUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostDataPiesDetails;
        
        #line default
        #line hidden
        
        
        #line 11 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelStatus;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelExchange;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSecurity;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelClass;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeFrame;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeStart;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeEnd;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeStartReal;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeEndReal;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelStatusValue;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelExchangeValue;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSecurityValue;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelClassValue;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeFrameValue;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeStartValue;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeEndValue;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeStartRealValue;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeEndRealValue;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\OsData\OsDataSetDetailUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCache;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/osdata/osdatasetdetailui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\OsData\OsDataSetDetailUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.HostDataPiesDetails = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 2:
            this.LabelStatus = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.LabelExchange = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.LabelSecurity = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.LabelClass = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.LabelTimeFrame = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.LabelTimeStart = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.LabelTimeEnd = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.LabelTimeStartReal = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.LabelTimeEndReal = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.LabelStatusValue = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.LabelExchangeValue = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.LabelSecurityValue = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.LabelClassValue = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.LabelTimeFrameValue = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.LabelTimeStartValue = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.LabelTimeEndValue = ((System.Windows.Controls.Label)(target));
            return;
            case 18:
            this.LabelTimeStartRealValue = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.LabelTimeEndRealValue = ((System.Windows.Controls.Label)(target));
            return;
            case 20:
            this.LabelCache = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

