#pragma checksum "..\..\..\OsOptimizer\OptimizerReportUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "45A4BACF208E34F55CD50039D9465412F40FB83D98D6BDBE1FE05212AA4744B4"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using OsEngine.OsOptimizer;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.OsOptimizer {
    
    
    /// <summary>
    /// OptimizerReportUi
    /// </summary>
    public partial class OptimizerReportUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 9 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridPrime;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControlPrime;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemResults;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControlResults;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabControlResultsSeries;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost WindowsFormsHostFazeNumOnTubResult;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelOptimSeries;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost WindowsFormsHostResults;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTableResults;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabControlResultsOutOfSampleResults;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PrimeGrid;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid BottomGrid;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostTotalProfit;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostRobustness;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelRobustnessMetric;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelRobustnessMetricValue;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTotalProfit;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxTotalProfit;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid LeftGrid;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostAverageProfit;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelAverageProfitPersent;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostProfitFactor;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelAverageProfitFactor;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostStepsOfOptimizationTable;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSortResultsType;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSortBy;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSortResultsBotNumPercent;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabControlResultsOutOfSampleResults1;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PrimeGrid1;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid BottomGrid1;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostTotalProfit1;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostFRS;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTotalProfit1;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxTotalProfit1;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonUpdateCSC;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid LeftGrid1;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostAverageProfit1;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelAverageProfitPersent1;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostProfitFactor1;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelAverageProfitFactor1;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostStepsOfOptimizationTable1;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSortResultsType1;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSortBy1;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSortResultsBotNumPercent1;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabControlResultsOutOfSampleResults2;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PrimeGrid2;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid BottomGrid2;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostTotalProfit2;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTotalProfit2;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxTotalProfit2;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbShowInSample;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostStepsOfOptimizationTable2;
        
        #line default
        #line hidden
        
        
        #line 106 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSortResultsType2;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSortBy2;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSortResultsBotNumPercent2;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbGroupPhazePeriods;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelOsa;
        
        #line default
        #line hidden
        
        
        #line 137 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxDataCapture;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonLoadFromFile;
        
        #line default
        #line hidden
        
        
        #line 139 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSaveInFile;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/osoptimizer/optimizerreportui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.GridPrime = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.TabControlPrime = ((System.Windows.Controls.TabControl)(target));
            return;
            case 3:
            this.TabItemResults = ((System.Windows.Controls.TabItem)(target));
            return;
            case 4:
            this.TabControlResults = ((System.Windows.Controls.TabControl)(target));
            return;
            case 5:
            this.TabControlResultsSeries = ((System.Windows.Controls.TabItem)(target));
            return;
            case 6:
            this.WindowsFormsHostFazeNumOnTubResult = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 7:
            this.LabelOptimSeries = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.WindowsFormsHostResults = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 9:
            this.LabelTableResults = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.TabControlResultsOutOfSampleResults = ((System.Windows.Controls.TabItem)(target));
            return;
            case 11:
            this.PrimeGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 12:
            this.BottomGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 13:
            this.HostTotalProfit = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 14:
            this.HostRobustness = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 15:
            this.LabelRobustnessMetric = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.LabelRobustnessMetricValue = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.LabelTotalProfit = ((System.Windows.Controls.Label)(target));
            return;
            case 18:
            this.ComboBoxTotalProfit = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 19:
            this.LeftGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 20:
            this.HostAverageProfit = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 21:
            this.LabelAverageProfitPersent = ((System.Windows.Controls.Label)(target));
            return;
            case 22:
            this.HostProfitFactor = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 23:
            this.LabelAverageProfitFactor = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.HostStepsOfOptimizationTable = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 25:
            this.ComboBoxSortResultsType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 26:
            this.LabelSortBy = ((System.Windows.Controls.Label)(target));
            return;
            case 27:
            this.ComboBoxSortResultsBotNumPercent = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 28:
            this.TabControlResultsOutOfSampleResults1 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 29:
            this.PrimeGrid1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 30:
            this.BottomGrid1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 31:
            this.HostTotalProfit1 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 32:
            this.HostFRS = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 33:
            this.LabelTotalProfit1 = ((System.Windows.Controls.Label)(target));
            return;
            case 34:
            this.ComboBoxTotalProfit1 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 35:
            this.ButtonUpdateCSC = ((System.Windows.Controls.Button)(target));
            
            #line 71 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
            this.ButtonUpdateCSC.Click += new System.Windows.RoutedEventHandler(this.ButtonUpdateCSC_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            this.LeftGrid1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 37:
            this.HostAverageProfit1 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 38:
            this.LabelAverageProfitPersent1 = ((System.Windows.Controls.Label)(target));
            return;
            case 39:
            this.HostProfitFactor1 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 40:
            this.LabelAverageProfitFactor1 = ((System.Windows.Controls.Label)(target));
            return;
            case 41:
            this.HostStepsOfOptimizationTable1 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 42:
            this.ComboBoxSortResultsType1 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 43:
            this.LabelSortBy1 = ((System.Windows.Controls.Label)(target));
            return;
            case 44:
            this.ComboBoxSortResultsBotNumPercent1 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 45:
            this.TabControlResultsOutOfSampleResults2 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 46:
            this.PrimeGrid2 = ((System.Windows.Controls.Grid)(target));
            return;
            case 47:
            this.BottomGrid2 = ((System.Windows.Controls.Grid)(target));
            return;
            case 48:
            this.HostTotalProfit2 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 49:
            this.LabelTotalProfit2 = ((System.Windows.Controls.Label)(target));
            return;
            case 50:
            this.ComboBoxTotalProfit2 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 51:
            this.cbShowInSample = ((System.Windows.Controls.CheckBox)(target));
            
            #line 103 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
            this.cbShowInSample.Checked += new System.Windows.RoutedEventHandler(this.cbShowInSample_Checked);
            
            #line default
            #line hidden
            
            #line 103 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
            this.cbShowInSample.Unchecked += new System.Windows.RoutedEventHandler(this.cbShowInSample_Checked);
            
            #line default
            #line hidden
            return;
            case 52:
            this.HostStepsOfOptimizationTable2 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 53:
            this.ComboBoxSortResultsType2 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 54:
            this.LabelSortBy2 = ((System.Windows.Controls.Label)(target));
            return;
            case 55:
            this.ComboBoxSortResultsBotNumPercent2 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 56:
            this.cbGroupPhazePeriods = ((System.Windows.Controls.CheckBox)(target));
            
            #line 109 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
            this.cbGroupPhazePeriods.Checked += new System.Windows.RoutedEventHandler(this.cbGroupPhazePeriods_Checked);
            
            #line default
            #line hidden
            
            #line 109 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
            this.cbGroupPhazePeriods.Unchecked += new System.Windows.RoutedEventHandler(this.cbGroupPhazePeriods_Checked);
            
            #line default
            #line hidden
            return;
            case 57:
            this.LabelOsa = ((System.Windows.Controls.Label)(target));
            return;
            case 58:
            this.CheckBoxDataCapture = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 59:
            this.ButtonLoadFromFile = ((System.Windows.Controls.Button)(target));
            
            #line 138 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
            this.ButtonLoadFromFile.Click += new System.Windows.RoutedEventHandler(this.ButtonLoadFromFile_Click);
            
            #line default
            #line hidden
            return;
            case 60:
            this.ButtonSaveInFile = ((System.Windows.Controls.Button)(target));
            
            #line 139 "..\..\..\OsOptimizer\OptimizerReportUi.xaml"
            this.ButtonSaveInFile.Click += new System.Windows.RoutedEventHandler(this.ButtonSaveInFile_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

