#pragma checksum "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "14DE9BF6FBB9EED24E12A4866584E370D2E67C0DEFC42D6B3D9C654E8B8EDCBB"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.Charts.CandleChart.Indicators {
    
    
    /// <summary>
    /// VwapUi
    /// </summary>
    public partial class VwapUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 8 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label DateSetting;
        
        #line default
        #line hidden
        
        
        #line 9 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox UseDate;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost DatePickerStart;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost TimePickerStart;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToEndTicks;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost DatePickerEnd;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost TimePickerEnd;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Deviations2;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Deviations3;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Deviations4;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonColorUp;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostColorUp;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonColorDown;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostColorDown;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox UseDay;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox DayDeviations2;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox DayDeviations3;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox DayDeviations4;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonColorDayUp;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostColorDayUp;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonColorDayDown;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostColorDayDown;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox UseWeekly;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox WeekDeviations2;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox WeekDeviations3;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox WeekDeviations4;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonColorWeekUp;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostColorWeekUp;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonColorWeekDown;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostColorWeekDown;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonAccept;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/charts/candlechart/indicators/vwapui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.DateSetting = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.UseDate = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 3:
            this.DatePickerStart = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 4:
            this.TimePickerStart = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 5:
            this.ToEndTicks = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.DatePickerEnd = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 7:
            this.TimePickerEnd = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 8:
            this.Deviations2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 9:
            this.Deviations3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 10:
            this.Deviations4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 11:
            this.ButtonColorUp = ((System.Windows.Controls.Button)(target));
            
            #line 36 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
            this.ButtonColorUp.Click += new System.Windows.RoutedEventHandler(this.ButtonColorUp_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.HostColorUp = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 13:
            this.ButtonColorDown = ((System.Windows.Controls.Button)(target));
            
            #line 38 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
            this.ButtonColorDown.Click += new System.Windows.RoutedEventHandler(this.ButtonColorDown_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.HostColorDown = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 15:
            this.UseDay = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 16:
            this.DayDeviations2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 17:
            this.DayDeviations3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 18:
            this.DayDeviations4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 19:
            this.ButtonColorDayUp = ((System.Windows.Controls.Button)(target));
            
            #line 48 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
            this.ButtonColorDayUp.Click += new System.Windows.RoutedEventHandler(this.ButtonColorDayUp_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.HostColorDayUp = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 21:
            this.ButtonColorDayDown = ((System.Windows.Controls.Button)(target));
            
            #line 50 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
            this.ButtonColorDayDown.Click += new System.Windows.RoutedEventHandler(this.ButtonColorDayDown_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.HostColorDayDown = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 23:
            this.UseWeekly = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 24:
            this.WeekDeviations2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 25:
            this.WeekDeviations3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 26:
            this.WeekDeviations4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 27:
            this.ButtonColorWeekUp = ((System.Windows.Controls.Button)(target));
            
            #line 60 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
            this.ButtonColorWeekUp.Click += new System.Windows.RoutedEventHandler(this.ButtonColorWeekUp_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.HostColorWeekUp = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 29:
            this.ButtonColorWeekDown = ((System.Windows.Controls.Button)(target));
            
            #line 62 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
            this.ButtonColorWeekDown.Click += new System.Windows.RoutedEventHandler(this.ButtonColorWeekDown_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.HostColorWeekDown = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 31:
            this.ButtonAccept = ((System.Windows.Controls.Button)(target));
            
            #line 65 "..\..\..\..\..\Charts\CandleChart\Indicators\VwapUi.xaml"
            this.ButtonAccept.Click += new System.Windows.RoutedEventHandler(this.ButtonAccept_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

