#pragma checksum "..\..\..\Robots\BotCreateUi2.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "CDD8B00722DE5E1F9A6D66ACABC5E11C150A974FEB3491E7571C52A013C6DE41"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using OsEngine.Robots;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.Robots {
    
    
    /// <summary>
    /// BotCreateUi2
    /// </summary>
    public partial class BotCreateUi2 : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 11 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonAccept;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxName;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelName;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostBots;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelLocation;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxLockation;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonWhyNeadName;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonWhyLocation;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxSearchSecurity;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRightInSearchResults;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonLeftInSearchResults;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCurrentResultShow;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCommasResultShow;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCountResultsShow;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\Robots\BotCreateUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonUpdateRobots;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/robots/botcreateui2.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Robots\BotCreateUi2.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ButtonAccept = ((System.Windows.Controls.Button)(target));
            
            #line 11 "..\..\..\Robots\BotCreateUi2.xaml"
            this.ButtonAccept.Click += new System.Windows.RoutedEventHandler(this.ButtonAccept_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.TextBoxName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.LabelName = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.HostBots = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 5:
            this.LabelLocation = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.ComboBoxLockation = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.ButtonWhyNeadName = ((System.Windows.Controls.Button)(target));
            
            #line 17 "..\..\..\Robots\BotCreateUi2.xaml"
            this.ButtonWhyNeadName.Click += new System.Windows.RoutedEventHandler(this.ButtonWhyNeadName_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ButtonWhyLocation = ((System.Windows.Controls.Button)(target));
            
            #line 18 "..\..\..\Robots\BotCreateUi2.xaml"
            this.ButtonWhyLocation.Click += new System.Windows.RoutedEventHandler(this.ButtonWhyLocation_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.TextBoxSearchSecurity = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.ButtonRightInSearchResults = ((System.Windows.Controls.Button)(target));
            return;
            case 11:
            this.ButtonLeftInSearchResults = ((System.Windows.Controls.Button)(target));
            return;
            case 12:
            this.LabelCurrentResultShow = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.LabelCommasResultShow = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.LabelCountResultsShow = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.ButtonUpdateRobots = ((System.Windows.Controls.Button)(target));
            
            #line 25 "..\..\..\Robots\BotCreateUi2.xaml"
            this.ButtonUpdateRobots.Click += new System.Windows.RoutedEventHandler(this.ButtonUpdateRobots_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

