#pragma checksum "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "3BE5F3B743E02F6B4D7D2F489E4BCA545BDF97AF3FDC5C7C1AF0F0CFC0936C8A"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using OsEngine.OsTrader.Gui;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.OsTrader.Gui {
    
    
    /// <summary>
    /// RobotUiLight
    /// </summary>
    public partial class RobotUiLight : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 9 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridPrime;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GreedPozitonLogHost;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControlPrime;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemAllPos;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabActivePos;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxGroupActive;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostActivePoses;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabStopLimitPoses;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostStopLimitPoses;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabHistoricalPos;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostHistoricalPoses;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabAllOrders;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabActiveOrders;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostActiveOrders;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabHistoricalOrders;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostHistoricalOrders;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabPortfolios;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostPortfolios;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemLogPrime;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostBotLogPrime;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemControl;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostServers;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostServerLog;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxServerAutoOpen;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSyncToTesterLight;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSupportTable;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelOsa;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GreedChartPanel;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost BotsHost;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle rectToMove;
        
        #line default
        #line hidden
        
        
        #line 116 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image ImagePadlock;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image ImagePadlockOpen;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/ostrader/gui/robotuilight.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.GridPrime = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.GreedPozitonLogHost = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.TabControlPrime = ((System.Windows.Controls.TabControl)(target));
            return;
            case 4:
            this.TabItemAllPos = ((System.Windows.Controls.TabItem)(target));
            return;
            case 5:
            this.TabActivePos = ((System.Windows.Controls.TabItem)(target));
            return;
            case 6:
            this.CheckBoxGroupActive = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.HostActivePoses = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 8:
            this.TabStopLimitPoses = ((System.Windows.Controls.TabItem)(target));
            return;
            case 9:
            this.HostStopLimitPoses = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 10:
            this.TabHistoricalPos = ((System.Windows.Controls.TabItem)(target));
            return;
            case 11:
            this.HostHistoricalPoses = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 12:
            this.TabAllOrders = ((System.Windows.Controls.TabItem)(target));
            return;
            case 13:
            this.TabActiveOrders = ((System.Windows.Controls.TabItem)(target));
            return;
            case 14:
            this.HostActiveOrders = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 15:
            this.TabHistoricalOrders = ((System.Windows.Controls.TabItem)(target));
            return;
            case 16:
            this.HostHistoricalOrders = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 17:
            this.TabPortfolios = ((System.Windows.Controls.TabItem)(target));
            return;
            case 18:
            this.HostPortfolios = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 19:
            this.TabItemLogPrime = ((System.Windows.Controls.TabItem)(target));
            return;
            case 20:
            this.HostBotLogPrime = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 21:
            this.TabItemControl = ((System.Windows.Controls.TabItem)(target));
            return;
            case 22:
            this.HostServers = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 23:
            this.HostServerLog = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 24:
            this.CheckBoxServerAutoOpen = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 25:
            this.ButtonSyncToTesterLight = ((System.Windows.Controls.Button)(target));
            
            #line 74 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
            this.ButtonSyncToTesterLight.Click += new System.Windows.RoutedEventHandler(this.ButtonSyncToTesterLight_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.ButtonSupportTable = ((System.Windows.Controls.Button)(target));
            
            #line 75 "..\..\..\..\OsTrader\Gui\RobotUiLight.xaml"
            this.ButtonSupportTable.Click += new System.Windows.RoutedEventHandler(this.ButtonSupportTable_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            this.LabelOsa = ((System.Windows.Controls.Label)(target));
            return;
            case 28:
            this.GreedChartPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 29:
            this.BotsHost = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 30:
            this.rectToMove = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 31:
            this.ImagePadlock = ((System.Windows.Controls.Image)(target));
            return;
            case 32:
            this.ImagePadlockOpen = ((System.Windows.Controls.Image)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

