#pragma checksum "..\..\..\OsOptimizer\OptimizerUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "782B6212C5161E40F3A34E529880DB155F8F14900725A87E1B860DFA28DBF611"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.OsOptimizer {
    
    
    /// <summary>
    /// OptimizerUi
    /// </summary>
    public partial class OptimizerUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 5 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridPrime;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGo;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar ProgressBarPrime;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label7;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridThreadsProgress;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxThreadsCount;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label8;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonResults;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControlPrime;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemControl;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxStartPortfolio;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label13;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label CommissionTypeLabel;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CommissionTypeComboBox;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label CommissionValueLabel;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CommissionValueTextBox;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostLog;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle RectangleTimeFramesAndSecurities;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostTabsSimple;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTabsEndTimeFrames;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle RectangleServerData;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonServerDialog;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle RectangleStrategyName;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label12;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostTabsIndex;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label15;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonStrategySelect;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxStrategyName;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonStrategyReload;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonPositionSupport;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxSaveJson;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxSaveCandles;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label SaveJsonPathLabel;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SaveJsonPath;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemParams;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridParametrs;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostParam;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label17;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelIteartionCount;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelIteartionCountNumber;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSetStandartParams;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemFazes;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridFazes;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControlFazes;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemFazes1;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostStepsOptimize;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DatePickerStart;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DatePickerEnd;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label20;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxPercentFiltration;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label21;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxIterationCount;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label23;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxLastInSample;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemFazes2;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonPhazePresetSave;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxPhazePresets;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostCustomPhazes;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxPositionsCountForWinRate;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonCreateOptimizeFazes;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostWalkForwardPeriods;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemFilters;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridFilters;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label22;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxFilterProfitIsOn;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxFilterMaxDrowDownIsOn;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxFilterMiddleProfitIsOn;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxFilterProfitFactorIsOn;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxFilterProfitValue;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxMaxDrowDownValue;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxFilterMiddleProfitValue;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxFilterProfitFactorValue;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxFilterDealsCount;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxFilterDealsCount;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemMlOptimizer;
        
        #line default
        #line hidden
        
        
        #line 120 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxRfSampleCount;
        
        #line default
        #line hidden
        
        
        #line 121 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRunRandomForest;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRunRandomForestAndRefine;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelRfPlanned;
        
        #line default
        #line hidden
        
        
        #line 124 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRefineAndRun;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelRefinedPlanned;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TextBlockRfMetrics;
        
        #line default
        #line hidden
        
        
        #line 128 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid DataGridRfImportances;
        
        #line default
        #line hidden
        
        
        #line 134 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid DataGridRfBestParams;
        
        #line default
        #line hidden
        
        
        #line 141 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid DataGridRefinedRanges;
        
        #line default
        #line hidden
        
        
        #line 150 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TextBlockRfStatus;
        
        #line default
        #line hidden
        
        
        #line 153 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemResults;
        
        #line default
        #line hidden
        
        
        #line 155 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControlResults;
        
        #line default
        #line hidden
        
        
        #line 156 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabControlResultsSeries;
        
        #line default
        #line hidden
        
        
        #line 158 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost WindowsFormsHostFazeNumOnTubResult;
        
        #line default
        #line hidden
        
        
        #line 159 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label30;
        
        #line default
        #line hidden
        
        
        #line 160 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost WindowsFormsHostResults;
        
        #line default
        #line hidden
        
        
        #line 161 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label31;
        
        #line default
        #line hidden
        
        
        #line 164 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabControlResultsOutOfSampleResults;
        
        #line default
        #line hidden
        
        
        #line 166 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostStepsOfOptimizationTable;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSortResultsType;
        
        #line default
        #line hidden
        
        
        #line 168 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSortBy;
        
        #line default
        #line hidden
        
        
        #line 169 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostRobustness;
        
        #line default
        #line hidden
        
        
        #line 170 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost WindowsFormsHostTotalProfit;
        
        #line default
        #line hidden
        
        
        #line 171 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelRobustnessMetric;
        
        #line default
        #line hidden
        
        
        #line 172 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelRobustnessMetricValue;
        
        #line default
        #line hidden
        
        
        #line 173 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTotalAbsProfit;
        
        #line default
        #line hidden
        
        
        #line 174 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxTotalProfit;
        
        #line default
        #line hidden
        
        
        #line 175 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSortResultsBotNumPercent;
        
        #line default
        #line hidden
        
        
        #line 178 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabControlResultsOutOfSampleResults1;
        
        #line default
        #line hidden
        
        
        #line 179 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PrimeGrid1;
        
        #line default
        #line hidden
        
        
        #line 180 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid BottomGrid1;
        
        #line default
        #line hidden
        
        
        #line 185 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostTotalProfit1;
        
        #line default
        #line hidden
        
        
        #line 186 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostFRS;
        
        #line default
        #line hidden
        
        
        #line 187 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTotalProfit1;
        
        #line default
        #line hidden
        
        
        #line 188 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxTotalProfit1;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonUpdateCSC;
        
        #line default
        #line hidden
        
        
        #line 191 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid LeftGrid1;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostAverageProfit1;
        
        #line default
        #line hidden
        
        
        #line 197 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelAverageProfitPersent1;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostProfitFactor1;
        
        #line default
        #line hidden
        
        
        #line 199 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelAverageProfitFactor1;
        
        #line default
        #line hidden
        
        
        #line 201 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostStepsOfOptimizationTable1;
        
        #line default
        #line hidden
        
        
        #line 202 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSortResultsType1;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSortBy1;
        
        #line default
        #line hidden
        
        
        #line 204 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSortResultsBotNumPercent1;
        
        #line default
        #line hidden
        
        
        #line 207 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabControlResultsOutOfSampleResults2;
        
        #line default
        #line hidden
        
        
        #line 208 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PrimeGrid2;
        
        #line default
        #line hidden
        
        
        #line 209 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid BottomGrid2;
        
        #line default
        #line hidden
        
        
        #line 214 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostTotalProfit2;
        
        #line default
        #line hidden
        
        
        #line 215 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTotalProfit2;
        
        #line default
        #line hidden
        
        
        #line 216 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxTotalProfit2;
        
        #line default
        #line hidden
        
        
        #line 217 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbShowInSample;
        
        #line default
        #line hidden
        
        
        #line 219 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostStepsOfOptimizationTable2;
        
        #line default
        #line hidden
        
        
        #line 220 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSortResultsType2;
        
        #line default
        #line hidden
        
        
        #line 221 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSortBy2;
        
        #line default
        #line hidden
        
        
        #line 222 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSortResultsBotNumPercent2;
        
        #line default
        #line hidden
        
        
        #line 223 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbGroupPhazePeriods;
        
        #line default
        #line hidden
        
        
        #line 227 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxDataCapture;
        
        #line default
        #line hidden
        
        
        #line 242 "..\..\..\OsOptimizer\OptimizerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelOsa;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/osoptimizer/optimizerui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.GridPrime = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.ButtonGo = ((System.Windows.Controls.Button)(target));
            
            #line 12 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.ButtonGo.Click += new System.Windows.RoutedEventHandler(this.ButtonGo_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.ProgressBarPrime = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 4:
            this.Label7 = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.GridThreadsProgress = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.ComboBoxThreadsCount = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.Label8 = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.ButtonResults = ((System.Windows.Controls.Button)(target));
            
            #line 18 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.ButtonResults.Click += new System.Windows.RoutedEventHandler(this.ButtonResults_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.TabControlPrime = ((System.Windows.Controls.TabControl)(target));
            return;
            case 10:
            this.TabItemControl = ((System.Windows.Controls.TabItem)(target));
            return;
            case 11:
            this.TextBoxStartPortfolio = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.Label13 = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.CommissionTypeLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.CommissionTypeComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 15:
            this.CommissionValueLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.CommissionValueTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.HostLog = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 18:
            this.RectangleTimeFramesAndSecurities = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 19:
            this.HostTabsSimple = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 20:
            this.LabelTabsEndTimeFrames = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.RectangleServerData = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 22:
            this.ButtonServerDialog = ((System.Windows.Controls.Button)(target));
            
            #line 35 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.ButtonServerDialog.Click += new System.Windows.RoutedEventHandler(this.ButtonServerDialog_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.RectangleStrategyName = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 24:
            this.Label12 = ((System.Windows.Controls.Label)(target));
            return;
            case 25:
            this.HostTabsIndex = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 26:
            this.Label15 = ((System.Windows.Controls.Label)(target));
            return;
            case 27:
            this.ButtonStrategySelect = ((System.Windows.Controls.Button)(target));
            
            #line 40 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.ButtonStrategySelect.Click += new System.Windows.RoutedEventHandler(this.ButtonStrategySelect_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.TextBoxStrategyName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 29:
            this.ButtonStrategyReload = ((System.Windows.Controls.Button)(target));
            
            #line 42 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.ButtonStrategyReload.Click += new System.Windows.RoutedEventHandler(this.ButtonStrategyReload_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.ButtonPositionSupport = ((System.Windows.Controls.Button)(target));
            
            #line 43 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.ButtonPositionSupport.Click += new System.Windows.RoutedEventHandler(this.ButtonPositionSupport_Click);
            
            #line default
            #line hidden
            return;
            case 31:
            this.CheckBoxSaveJson = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 32:
            this.CheckBoxSaveCandles = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 33:
            this.SaveJsonPathLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 34:
            this.SaveJsonPath = ((System.Windows.Controls.TextBox)(target));
            return;
            case 35:
            this.TabItemParams = ((System.Windows.Controls.TabItem)(target));
            return;
            case 36:
            this.GridParametrs = ((System.Windows.Controls.Grid)(target));
            return;
            case 37:
            this.HostParam = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 38:
            this.Label17 = ((System.Windows.Controls.Label)(target));
            return;
            case 39:
            this.LabelIteartionCount = ((System.Windows.Controls.Label)(target));
            return;
            case 40:
            this.LabelIteartionCountNumber = ((System.Windows.Controls.Label)(target));
            return;
            case 41:
            this.ButtonSetStandartParams = ((System.Windows.Controls.Button)(target));
            
            #line 56 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.ButtonSetStandartParams.Click += new System.Windows.RoutedEventHandler(this.ButtonSetStandartParams_Click);
            
            #line default
            #line hidden
            return;
            case 42:
            this.TabItemFazes = ((System.Windows.Controls.TabItem)(target));
            return;
            case 43:
            this.GridFazes = ((System.Windows.Controls.Grid)(target));
            return;
            case 44:
            this.TabControlFazes = ((System.Windows.Controls.TabControl)(target));
            return;
            case 45:
            this.TabItemFazes1 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 46:
            this.HostStepsOptimize = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 47:
            this.DatePickerStart = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 48:
            this.DatePickerEnd = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 49:
            this.Label20 = ((System.Windows.Controls.Label)(target));
            return;
            case 50:
            this.TextBoxPercentFiltration = ((System.Windows.Controls.TextBox)(target));
            return;
            case 51:
            this.Label21 = ((System.Windows.Controls.Label)(target));
            return;
            case 52:
            this.TextBoxIterationCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 53:
            this.Label23 = ((System.Windows.Controls.Label)(target));
            return;
            case 54:
            this.CheckBoxLastInSample = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 55:
            this.TabItemFazes2 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 56:
            this.ButtonPhazePresetSave = ((System.Windows.Controls.Button)(target));
            
            #line 77 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.ButtonPhazePresetSave.Click += new System.Windows.RoutedEventHandler(this.ButtonSave_Click);
            
            #line default
            #line hidden
            return;
            case 57:
            this.ComboBoxPhazePresets = ((System.Windows.Controls.ComboBox)(target));
            
            #line 79 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.ComboBoxPhazePresets.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ComboBoxPhazePresets_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 58:
            this.HostCustomPhazes = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 59:
            this.TextBoxPositionsCountForWinRate = ((System.Windows.Controls.TextBox)(target));
            
            #line 81 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.TextBoxPositionsCountForWinRate.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxPositionsCountForWinRate_TextChanged);
            
            #line default
            #line hidden
            return;
            case 60:
            this.ButtonCreateOptimizeFazes = ((System.Windows.Controls.Button)(target));
            
            #line 88 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.ButtonCreateOptimizeFazes.Click += new System.Windows.RoutedEventHandler(this.ButtonCreateOptimizeFazes_Click);
            
            #line default
            #line hidden
            return;
            case 61:
            this.HostWalkForwardPeriods = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 62:
            this.TabItemFilters = ((System.Windows.Controls.TabItem)(target));
            return;
            case 63:
            this.GridFilters = ((System.Windows.Controls.Grid)(target));
            return;
            case 64:
            this.Label22 = ((System.Windows.Controls.Label)(target));
            return;
            case 65:
            this.CheckBoxFilterProfitIsOn = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 66:
            this.CheckBoxFilterMaxDrowDownIsOn = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 67:
            this.CheckBoxFilterMiddleProfitIsOn = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 68:
            this.CheckBoxFilterProfitFactorIsOn = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 69:
            this.TextBoxFilterProfitValue = ((System.Windows.Controls.TextBox)(target));
            return;
            case 70:
            this.TextBoxMaxDrowDownValue = ((System.Windows.Controls.TextBox)(target));
            return;
            case 71:
            this.TextBoxFilterMiddleProfitValue = ((System.Windows.Controls.TextBox)(target));
            return;
            case 72:
            this.TextBoxFilterProfitFactorValue = ((System.Windows.Controls.TextBox)(target));
            return;
            case 73:
            this.CheckBoxFilterDealsCount = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 74:
            this.TextBoxFilterDealsCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 75:
            this.TabItemMlOptimizer = ((System.Windows.Controls.TabItem)(target));
            return;
            case 76:
            this.TextBoxRfSampleCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 77:
            this.ButtonRunRandomForest = ((System.Windows.Controls.Button)(target));
            return;
            case 78:
            this.ButtonRunRandomForestAndRefine = ((System.Windows.Controls.Button)(target));
            return;
            case 79:
            this.LabelRfPlanned = ((System.Windows.Controls.Label)(target));
            return;
            case 80:
            this.ButtonRefineAndRun = ((System.Windows.Controls.Button)(target));
            return;
            case 81:
            this.LabelRefinedPlanned = ((System.Windows.Controls.Label)(target));
            return;
            case 82:
            this.TextBlockRfMetrics = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 83:
            this.DataGridRfImportances = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 84:
            this.DataGridRfBestParams = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 85:
            this.DataGridRefinedRanges = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 86:
            this.TextBlockRfStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 87:
            this.TabItemResults = ((System.Windows.Controls.TabItem)(target));
            return;
            case 88:
            this.TabControlResults = ((System.Windows.Controls.TabControl)(target));
            return;
            case 89:
            this.TabControlResultsSeries = ((System.Windows.Controls.TabItem)(target));
            return;
            case 90:
            this.WindowsFormsHostFazeNumOnTubResult = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 91:
            this.Label30 = ((System.Windows.Controls.Label)(target));
            return;
            case 92:
            this.WindowsFormsHostResults = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 93:
            this.Label31 = ((System.Windows.Controls.Label)(target));
            return;
            case 94:
            this.TabControlResultsOutOfSampleResults = ((System.Windows.Controls.TabItem)(target));
            return;
            case 95:
            this.HostStepsOfOptimizationTable = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 96:
            this.ComboBoxSortResultsType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 97:
            this.LabelSortBy = ((System.Windows.Controls.Label)(target));
            return;
            case 98:
            this.HostRobustness = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 99:
            this.WindowsFormsHostTotalProfit = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 100:
            this.LabelRobustnessMetric = ((System.Windows.Controls.Label)(target));
            return;
            case 101:
            this.LabelRobustnessMetricValue = ((System.Windows.Controls.Label)(target));
            return;
            case 102:
            this.LabelTotalAbsProfit = ((System.Windows.Controls.Label)(target));
            return;
            case 103:
            this.ComboBoxTotalProfit = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 104:
            this.ComboBoxSortResultsBotNumPercent = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 105:
            this.TabControlResultsOutOfSampleResults1 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 106:
            this.PrimeGrid1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 107:
            this.BottomGrid1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 108:
            this.HostTotalProfit1 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 109:
            this.HostFRS = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 110:
            this.LabelTotalProfit1 = ((System.Windows.Controls.Label)(target));
            return;
            case 111:
            this.ComboBoxTotalProfit1 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 112:
            this.ButtonUpdateCSC = ((System.Windows.Controls.Button)(target));
            
            #line 189 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.ButtonUpdateCSC.Click += new System.Windows.RoutedEventHandler(this.ButtonUpdateCSC_Click);
            
            #line default
            #line hidden
            return;
            case 113:
            this.LeftGrid1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 114:
            this.HostAverageProfit1 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 115:
            this.LabelAverageProfitPersent1 = ((System.Windows.Controls.Label)(target));
            return;
            case 116:
            this.HostProfitFactor1 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 117:
            this.LabelAverageProfitFactor1 = ((System.Windows.Controls.Label)(target));
            return;
            case 118:
            this.HostStepsOfOptimizationTable1 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 119:
            this.ComboBoxSortResultsType1 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 120:
            this.LabelSortBy1 = ((System.Windows.Controls.Label)(target));
            return;
            case 121:
            this.ComboBoxSortResultsBotNumPercent1 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 122:
            this.TabControlResultsOutOfSampleResults2 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 123:
            this.PrimeGrid2 = ((System.Windows.Controls.Grid)(target));
            return;
            case 124:
            this.BottomGrid2 = ((System.Windows.Controls.Grid)(target));
            return;
            case 125:
            this.HostTotalProfit2 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 126:
            this.LabelTotalProfit2 = ((System.Windows.Controls.Label)(target));
            return;
            case 127:
            this.ComboBoxTotalProfit2 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 128:
            this.cbShowInSample = ((System.Windows.Controls.CheckBox)(target));
            
            #line 217 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.cbShowInSample.Checked += new System.Windows.RoutedEventHandler(this.cbShowInSample_Checked);
            
            #line default
            #line hidden
            
            #line 217 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.cbShowInSample.Unchecked += new System.Windows.RoutedEventHandler(this.cbShowInSample_Checked);
            
            #line default
            #line hidden
            return;
            case 129:
            this.HostStepsOfOptimizationTable2 = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 130:
            this.ComboBoxSortResultsType2 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 131:
            this.LabelSortBy2 = ((System.Windows.Controls.Label)(target));
            return;
            case 132:
            this.ComboBoxSortResultsBotNumPercent2 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 133:
            this.cbGroupPhazePeriods = ((System.Windows.Controls.CheckBox)(target));
            
            #line 223 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.cbGroupPhazePeriods.Checked += new System.Windows.RoutedEventHandler(this.cbGroupPhazePeriods_Checked);
            
            #line default
            #line hidden
            
            #line 223 "..\..\..\OsOptimizer\OptimizerUi.xaml"
            this.cbGroupPhazePeriods.Unchecked += new System.Windows.RoutedEventHandler(this.cbGroupPhazePeriods_Checked);
            
            #line default
            #line hidden
            return;
            case 134:
            this.CheckBoxDataCapture = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 135:
            this.LabelOsa = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

