#pragma checksum "..\..\..\OsData\NewSecurityUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "6C8DA15BDA4AF1247B1FFD315C7FA9559D30DC7CB5B5BC2CE76C5FEE3786E1B3"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.OsData {
    
    
    /// <summary>
    /// NewSecurityUi
    /// </summary>
    public partial class NewSecurityUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 7 "..\..\..\OsData\NewSecurityUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label1;
        
        #line default
        #line hidden
        
        
        #line 8 "..\..\..\OsData\NewSecurityUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonAccept;
        
        #line default
        #line hidden
        
        
        #line 9 "..\..\..\OsData\NewSecurityUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxClass;
        
        #line default
        #line hidden
        
        
        #line 10 "..\..\..\OsData\NewSecurityUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostSecurity;
        
        #line default
        #line hidden
        
        
        #line 11 "..\..\..\OsData\NewSecurityUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSearchString;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\OsData\NewSecurityUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxSelectAllCheckBox;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\OsData\NewSecurityUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxSearchSecurity;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\OsData\NewSecurityUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRightInSearchResults;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\OsData\NewSecurityUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonLeftInSearchResults;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\OsData\NewSecurityUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCurrentResultShow;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\OsData\NewSecurityUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCommasResultShow;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\OsData\NewSecurityUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCountResultsShow;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/osdata/newsecurityui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\OsData\NewSecurityUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Label1 = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.ButtonAccept = ((System.Windows.Controls.Button)(target));
            
            #line 8 "..\..\..\OsData\NewSecurityUi.xaml"
            this.ButtonAccept.Click += new System.Windows.RoutedEventHandler(this.ButtonAccept_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.ComboBoxClass = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 4:
            this.HostSecurity = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 5:
            this.LabelSearchString = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.CheckBoxSelectAllCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.TextBoxSearchSecurity = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.ButtonRightInSearchResults = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.ButtonLeftInSearchResults = ((System.Windows.Controls.Button)(target));
            return;
            case 10:
            this.LabelCurrentResultShow = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.LabelCommasResultShow = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.LabelCountResultsShow = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

