#pragma checksum "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "3E2E7E929F2C5CF8E452966ABAC745128C6FF3332096D6C493F27071A98B4518"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using OsEngine.OsTrader.Panels.Tab.Internal;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.OsTrader.Panels.Tab.Internal {
    
    
    /// <summary>
    /// PositionOpenUi2
    /// </summary>
    public partial class PositionOpenUi2 : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 11 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelServerType;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelServerTypeValue;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSecurity;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSecurityValue;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTabName;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTabNameValue;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxIsEmulator;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControlTypePosition;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemLimit;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxLimitPrice;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxLimitVolume;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelLimitPrice;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelLimitVolume;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemMarket;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxMarketVolume;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelMarketVolume;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemStopLimit;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxStopActivationPrice;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelStopActivationPrice;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxStopPrice;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelStopPrice;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxStopVolume;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelStopVolume;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxStopLimitType;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelStopActivationType;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxStopLifeTime;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelStopLifeTime;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxStopLifetimeType;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelStopLifeTimeType;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemFake;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxFakePrice;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxFakeVolume;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelFakePrice;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelFakeVolume;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DatePickerFakeOpenDate;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelFakeOpenDate;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxFakeOpenTime;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelFakeOpenTime;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonFakeTimeOpenNow;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSell;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonBuy;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost WinFormsHostMarketDepth;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/ostrader/panels/tab/internal/positionopenui2.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.LabelServerType = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.LabelServerTypeValue = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.LabelSecurity = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.LabelSecurityValue = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.LabelTabName = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.LabelTabNameValue = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.CheckBoxIsEmulator = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 8:
            this.TabControlTypePosition = ((System.Windows.Controls.TabControl)(target));
            return;
            case 9:
            this.TabItemLimit = ((System.Windows.Controls.TabItem)(target));
            return;
            case 10:
            this.TextBoxLimitPrice = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.TextBoxLimitVolume = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.LabelLimitPrice = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.LabelLimitVolume = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.TabItemMarket = ((System.Windows.Controls.TabItem)(target));
            return;
            case 15:
            this.TextBoxMarketVolume = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.LabelMarketVolume = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.TabItemStopLimit = ((System.Windows.Controls.TabItem)(target));
            return;
            case 18:
            this.TextBoxStopActivationPrice = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.LabelStopActivationPrice = ((System.Windows.Controls.Label)(target));
            return;
            case 20:
            this.TextBoxStopPrice = ((System.Windows.Controls.TextBox)(target));
            return;
            case 21:
            this.LabelStopPrice = ((System.Windows.Controls.Label)(target));
            return;
            case 22:
            this.TextBoxStopVolume = ((System.Windows.Controls.TextBox)(target));
            return;
            case 23:
            this.LabelStopVolume = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.ComboBoxStopLimitType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 25:
            this.LabelStopActivationType = ((System.Windows.Controls.Label)(target));
            return;
            case 26:
            this.TextBoxStopLifeTime = ((System.Windows.Controls.TextBox)(target));
            return;
            case 27:
            this.LabelStopLifeTime = ((System.Windows.Controls.Label)(target));
            return;
            case 28:
            this.ComboBoxStopLifetimeType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 29:
            this.LabelStopLifeTimeType = ((System.Windows.Controls.Label)(target));
            return;
            case 30:
            this.TabItemFake = ((System.Windows.Controls.TabItem)(target));
            return;
            case 31:
            this.TextBoxFakePrice = ((System.Windows.Controls.TextBox)(target));
            return;
            case 32:
            this.TextBoxFakeVolume = ((System.Windows.Controls.TextBox)(target));
            return;
            case 33:
            this.LabelFakePrice = ((System.Windows.Controls.Label)(target));
            return;
            case 34:
            this.LabelFakeVolume = ((System.Windows.Controls.Label)(target));
            return;
            case 35:
            this.DatePickerFakeOpenDate = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 36:
            this.LabelFakeOpenDate = ((System.Windows.Controls.Label)(target));
            return;
            case 37:
            this.TextBoxFakeOpenTime = ((System.Windows.Controls.TextBox)(target));
            return;
            case 38:
            this.LabelFakeOpenTime = ((System.Windows.Controls.Label)(target));
            return;
            case 39:
            this.ButtonFakeTimeOpenNow = ((System.Windows.Controls.Button)(target));
            
            #line 70 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
            this.ButtonFakeTimeOpenNow.Click += new System.Windows.RoutedEventHandler(this.ButtonFakeTimeOpenNow_Click);
            
            #line default
            #line hidden
            return;
            case 40:
            this.ButtonSell = ((System.Windows.Controls.Button)(target));
            
            #line 75 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
            this.ButtonSell.Click += new System.Windows.RoutedEventHandler(this.ButtonSell_Click);
            
            #line default
            #line hidden
            return;
            case 41:
            this.ButtonBuy = ((System.Windows.Controls.Button)(target));
            
            #line 76 "..\..\..\..\..\..\OsTrader\Panels\Tab\Internal\PositionOpenUi2.xaml"
            this.ButtonBuy.Click += new System.Windows.RoutedEventHandler(this.ButtonBuy_Click);
            
            #line default
            #line hidden
            return;
            case 42:
            this.WinFormsHostMarketDepth = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

