#pragma checksum "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "4D3C724FE222E05F809C2F2B469DFB7EB01351656F25C7B1C0CC5CEE70937059"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.Market.Servers.Tester {
    
    
    /// <summary>
    /// TesterServerUi
    /// </summary>
    public partial class TesterServerUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 12 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSynchronizer;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonFast;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonNextCandle;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonPausePlay;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonStartTest;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar ProgressBar;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label21;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelStatus;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem Label29;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostSecurities;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSets;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label28;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxDataType;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label25;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSetDataFromPath;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxDataPath;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxDataSourceType;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label24;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SliderFrom;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SliderTo;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxFrom;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxTo;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelFrom;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTo;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxRemoveTrades;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SecuritiesSettings;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem Label30;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridOrdersSettings;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxSlipageSimpleOrder;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label32;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxSlipageLimitOff;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxSlipageLimitOn;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxSlipageStop;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label33;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxSlipageStopOff;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxSlipageStopOn;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label34;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxOrderActivationType;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelOrderActivationType;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostClearing;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostNonTradePeriods;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelNonTradePeriod;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelClearing;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem Label31;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostPortfolio;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label40;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxStartDepozit;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxOnOffMarketPortfolio;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem Label23;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost Host;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGoTo;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonNextPos;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/market/servers/tester/testerserverui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ButtonSynchronizer = ((System.Windows.Controls.Button)(target));
            
            #line 12 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.ButtonSynchronizer.Click += new System.Windows.RoutedEventHandler(this.ButtonSynchronizer_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.ButtonFast = ((System.Windows.Controls.Button)(target));
            
            #line 13 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.ButtonFast.Click += new System.Windows.RoutedEventHandler(this.buttonFast_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.ButtonNextCandle = ((System.Windows.Controls.Button)(target));
            
            #line 15 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.ButtonNextCandle.Click += new System.Windows.RoutedEventHandler(this.buttonNextCandle_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ButtonPausePlay = ((System.Windows.Controls.Button)(target));
            
            #line 16 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.ButtonPausePlay.Click += new System.Windows.RoutedEventHandler(this.buttonPausePlay_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ButtonStartTest = ((System.Windows.Controls.Button)(target));
            
            #line 17 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.ButtonStartTest.Click += new System.Windows.RoutedEventHandler(this.buttonStartTest_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.ProgressBar = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 7:
            this.Label21 = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.LabelStatus = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.Label29 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 10:
            this.HostSecurities = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 11:
            this.ComboBoxSets = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 12:
            this.Label28 = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.ComboBoxDataType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 14:
            this.Label25 = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.ButtonSetDataFromPath = ((System.Windows.Controls.Button)(target));
            
            #line 29 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.ButtonSetDataFromPath.Click += new System.Windows.RoutedEventHandler(this.ButtonSetDataFromPath_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.TextBoxDataPath = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.ComboBoxDataSourceType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 18:
            this.Label24 = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.SliderFrom = ((System.Windows.Controls.Slider)(target));
            return;
            case 20:
            this.SliderTo = ((System.Windows.Controls.Slider)(target));
            return;
            case 21:
            this.TextBoxFrom = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.TextBoxTo = ((System.Windows.Controls.TextBox)(target));
            return;
            case 23:
            this.LabelFrom = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.LabelTo = ((System.Windows.Controls.Label)(target));
            return;
            case 25:
            this.CheckBoxRemoveTrades = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 26:
            this.SecuritiesSettings = ((System.Windows.Controls.Button)(target));
            
            #line 50 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.SecuritiesSettings.Click += new System.Windows.RoutedEventHandler(this.SecuritiesSettings_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            this.Label30 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 28:
            this.GridOrdersSettings = ((System.Windows.Controls.Grid)(target));
            return;
            case 29:
            this.TextBoxSlipageSimpleOrder = ((System.Windows.Controls.TextBox)(target));
            return;
            case 30:
            this.Label32 = ((System.Windows.Controls.Label)(target));
            return;
            case 31:
            this.CheckBoxSlipageLimitOff = ((System.Windows.Controls.CheckBox)(target));
            
            #line 62 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.CheckBoxSlipageLimitOff.Checked += new System.Windows.RoutedEventHandler(this.CheckBoxSlippageLimitOff_Checked);
            
            #line default
            #line hidden
            return;
            case 32:
            this.CheckBoxSlipageLimitOn = ((System.Windows.Controls.CheckBox)(target));
            
            #line 63 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.CheckBoxSlipageLimitOn.Checked += new System.Windows.RoutedEventHandler(this.CheckBoxSlippageLimitOn_Checked);
            
            #line default
            #line hidden
            return;
            case 33:
            this.TextBoxSlipageStop = ((System.Windows.Controls.TextBox)(target));
            return;
            case 34:
            this.Label33 = ((System.Windows.Controls.Label)(target));
            return;
            case 35:
            this.CheckBoxSlipageStopOff = ((System.Windows.Controls.CheckBox)(target));
            
            #line 66 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.CheckBoxSlipageStopOff.Checked += new System.Windows.RoutedEventHandler(this.CheckBoxSlippageStopOff_Checked);
            
            #line default
            #line hidden
            return;
            case 36:
            this.CheckBoxSlipageStopOn = ((System.Windows.Controls.CheckBox)(target));
            
            #line 67 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.CheckBoxSlipageStopOn.Checked += new System.Windows.RoutedEventHandler(this.CheckBoxSlippageStopOn_Checked);
            
            #line default
            #line hidden
            return;
            case 37:
            this.Label34 = ((System.Windows.Controls.Label)(target));
            return;
            case 38:
            this.ComboBoxOrderActivationType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 39:
            this.LabelOrderActivationType = ((System.Windows.Controls.Label)(target));
            return;
            case 40:
            this.HostClearing = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 41:
            this.HostNonTradePeriods = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 42:
            this.LabelNonTradePeriod = ((System.Windows.Controls.Label)(target));
            return;
            case 43:
            this.LabelClearing = ((System.Windows.Controls.Label)(target));
            return;
            case 44:
            this.Label31 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 45:
            this.HostPortfolio = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 46:
            this.Label40 = ((System.Windows.Controls.Label)(target));
            return;
            case 47:
            this.TextBoxStartDepozit = ((System.Windows.Controls.TextBox)(target));
            return;
            case 48:
            this.CheckBoxOnOffMarketPortfolio = ((System.Windows.Controls.CheckBox)(target));
            
            #line 89 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.CheckBoxOnOffMarketPortfolio.Click += new System.Windows.RoutedEventHandler(this.CheckBoxOnOffMarketPortfolio_Checked);
            
            #line default
            #line hidden
            return;
            case 49:
            this.Label23 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 50:
            this.Host = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 51:
            this.ButtonGoTo = ((System.Windows.Controls.Button)(target));
            
            #line 98 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.ButtonGoTo.Click += new System.Windows.RoutedEventHandler(this.ButtonGoTo_Click);
            
            #line default
            #line hidden
            return;
            case 52:
            this.ButtonNextPos = ((System.Windows.Controls.Button)(target));
            
            #line 99 "..\..\..\..\..\Market\Servers\Tester\TesterServerUi.xaml"
            this.ButtonNextPos.Click += new System.Windows.RoutedEventHandler(this.ButtonNextPos_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

