#pragma checksum "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0D2C20EE6492ADA56F04AC784092BAFB3AC62E60BAD4D5C4F50E1C3D518D76C9"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.Market.Connectors {
    
    
    /// <summary>
    /// ConnectorCandlesUi
    /// </summary>
    public partial class ConnectorCandlesUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 14 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label1;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxTypeServer;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label3;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxPortfolio;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label6;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxClass;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxIsEmulator;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonAccept;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label2;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label5;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelComissionType;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxComissionType;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelComissionValue;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxComissionValue;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost SecurityTable;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxSearchSecurity;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridCandleType;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label8;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxCandleMarketDataType;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label9;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxCandleCreateMethodType;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxSaveTradeArrayInCandle;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCandleType;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostCandleSeriesParameters;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRightInSearchResults;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonLeftInSearchResults;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCurrentResultShow;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCommasResultShow;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCountResultsShow;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/market/connectors/connectorcandlesui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Label1 = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.ComboBoxTypeServer = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 3:
            this.Label3 = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.ComboBoxPortfolio = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.Label6 = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.ComboBoxClass = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.CheckBoxIsEmulator = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 8:
            this.ButtonAccept = ((System.Windows.Controls.Button)(target));
            
            #line 25 "..\..\..\..\Market\Connectors\ConnectorCandlesUi.xaml"
            this.ButtonAccept.Click += new System.Windows.RoutedEventHandler(this.ButtonAccept_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.Label2 = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.Label5 = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.LabelComissionType = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.ComboBoxComissionType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 13:
            this.LabelComissionValue = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.TextBoxComissionValue = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.SecurityTable = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 16:
            this.TextBoxSearchSecurity = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.GridCandleType = ((System.Windows.Controls.Grid)(target));
            return;
            case 18:
            this.Label8 = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.ComboBoxCandleMarketDataType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 20:
            this.Label9 = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.ComboBoxCandleCreateMethodType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 22:
            this.CheckBoxSaveTradeArrayInCandle = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 23:
            this.LabelCandleType = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.HostCandleSeriesParameters = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 25:
            this.ButtonRightInSearchResults = ((System.Windows.Controls.Button)(target));
            return;
            case 26:
            this.ButtonLeftInSearchResults = ((System.Windows.Controls.Button)(target));
            return;
            case 27:
            this.LabelCurrentResultShow = ((System.Windows.Controls.Label)(target));
            return;
            case 28:
            this.LabelCommasResultShow = ((System.Windows.Controls.Label)(target));
            return;
            case 29:
            this.LabelCountResultsShow = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

