#pragma checksum "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "8B4C5ADA4BD2CDB5E283DAA709AC7D947CF5D0EC6A63D864ECADE75341EE4B2E"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.OsTrader.Panels {
    
    
    /// <summary>
    /// BotPanelChartUi
    /// </summary>
    public partial class BotPanelChartUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 5 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridPrime;
        
        #line default
        #line hidden
        
        
        #line 10 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GreedTraderEngine;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemMarketDepth;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonBuyFast;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSellFast;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxVolumeFast;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostGlass;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonBuyLimit;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSellLimit;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxPrice;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonCloseLimit;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonMoreOpenPositionDetail;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxVolumeInterText;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxPriceText;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemAlerts;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostAllert;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemControl;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelGeneralSettings;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonStrategSettings;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonJournalCommunity;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonStrategParametr;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRiskManager;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRedactTab;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonStrategSettingsIndividual;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonLoadJson;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxDirectoryPath;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label1;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GreedPozitonLogHost;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle rectToMove;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControlPrime;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabPozition;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostOpenPosition;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemStopLimits;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostStopLimits;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemClosedPos;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostClosePosition;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItemLogBot;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostBotLog;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelOsa;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControlBotsName;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GreedChartPanel;
        
        #line default
        #line hidden
        
        
        #line 110 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle RectChart;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridChart;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonShowInformPanel;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost ChartHostPanel;
        
        #line default
        #line hidden
        
        
        #line 124 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControlBotTab;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridChartControlPanel;
        
        #line default
        #line hidden
        
        
        #line 131 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonHideInformPanel;
        
        #line default
        #line hidden
        
        
        #line 141 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonHideShowSettingsPanel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/ostrader/panels/botpanelchartui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.GridPrime = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.GreedTraderEngine = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.TabItemMarketDepth = ((System.Windows.Controls.TabItem)(target));
            return;
            case 4:
            this.ButtonBuyFast = ((System.Windows.Controls.Button)(target));
            
            #line 14 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonBuyFast.Click += new System.Windows.RoutedEventHandler(this.buttonBuyFast_Click_1);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ButtonSellFast = ((System.Windows.Controls.Button)(target));
            
            #line 15 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonSellFast.Click += new System.Windows.RoutedEventHandler(this.buttonSellFast_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.TextBoxVolumeFast = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.HostGlass = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 8:
            this.ButtonBuyLimit = ((System.Windows.Controls.Button)(target));
            
            #line 18 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonBuyLimit.Click += new System.Windows.RoutedEventHandler(this.ButtonBuyLimit_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.ButtonSellLimit = ((System.Windows.Controls.Button)(target));
            
            #line 19 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonSellLimit.Click += new System.Windows.RoutedEventHandler(this.ButtonSellLimit_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.TextBoxPrice = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.ButtonCloseLimit = ((System.Windows.Controls.Button)(target));
            
            #line 21 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonCloseLimit.Click += new System.Windows.RoutedEventHandler(this.ButtonCloseLimit_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.ButtonMoreOpenPositionDetail = ((System.Windows.Controls.Button)(target));
            
            #line 22 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonMoreOpenPositionDetail.Click += new System.Windows.RoutedEventHandler(this.ButtonMoreOpenPositionDetail_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.TextBoxVolumeInterText = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.TextBoxPriceText = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.TabItemAlerts = ((System.Windows.Controls.TabItem)(target));
            return;
            case 16:
            this.HostAllert = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 17:
            this.TabItemControl = ((System.Windows.Controls.TabItem)(target));
            return;
            case 18:
            this.LabelGeneralSettings = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.ButtonStrategSettings = ((System.Windows.Controls.Button)(target));
            
            #line 37 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonStrategSettings.Click += new System.Windows.RoutedEventHandler(this.ButtonStrategManualSettings_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.ButtonJournalCommunity = ((System.Windows.Controls.Button)(target));
            
            #line 38 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonJournalCommunity.Click += new System.Windows.RoutedEventHandler(this.ButtonJournalCommunity_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.ButtonStrategParametr = ((System.Windows.Controls.Button)(target));
            
            #line 39 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonStrategParametr.Click += new System.Windows.RoutedEventHandler(this.ButtonStrategParametr_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.ButtonRiskManager = ((System.Windows.Controls.Button)(target));
            
            #line 40 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonRiskManager.Click += new System.Windows.RoutedEventHandler(this.ButtonRiskManager_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.ButtonRedactTab = ((System.Windows.Controls.Button)(target));
            
            #line 41 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonRedactTab.Click += new System.Windows.RoutedEventHandler(this.ButtonRedactTab_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.ButtonStrategSettingsIndividual = ((System.Windows.Controls.Button)(target));
            
            #line 42 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonStrategSettingsIndividual.Click += new System.Windows.RoutedEventHandler(this.ButtonStrategIndividualSettings_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.ButtonLoadJson = ((System.Windows.Controls.Button)(target));
            
            #line 43 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonLoadJson.Click += new System.Windows.RoutedEventHandler(this.ButtonJson_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.TextBoxDirectoryPath = ((System.Windows.Controls.TextBox)(target));
            return;
            case 27:
            this.Label1 = ((System.Windows.Controls.Label)(target));
            return;
            case 28:
            this.GreedPozitonLogHost = ((System.Windows.Controls.Grid)(target));
            return;
            case 29:
            this.rectToMove = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 30:
            this.TabControlPrime = ((System.Windows.Controls.TabControl)(target));
            return;
            case 31:
            this.TabPozition = ((System.Windows.Controls.TabItem)(target));
            return;
            case 32:
            this.HostOpenPosition = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 33:
            this.TabItemStopLimits = ((System.Windows.Controls.TabItem)(target));
            return;
            case 34:
            this.HostStopLimits = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 35:
            this.TabItemClosedPos = ((System.Windows.Controls.TabItem)(target));
            return;
            case 36:
            this.HostClosePosition = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 37:
            this.TabItemLogBot = ((System.Windows.Controls.TabItem)(target));
            return;
            case 38:
            this.HostBotLog = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 39:
            this.LabelOsa = ((System.Windows.Controls.Label)(target));
            return;
            case 40:
            this.TabControlBotsName = ((System.Windows.Controls.TabControl)(target));
            return;
            case 41:
            this.GreedChartPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 42:
            this.RectChart = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 43:
            this.GridChart = ((System.Windows.Controls.Grid)(target));
            return;
            case 44:
            this.ButtonShowInformPanel = ((System.Windows.Controls.Button)(target));
            
            #line 112 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonShowInformPanel.Click += new System.Windows.RoutedEventHandler(this.ButtonShowInformPanel_Click);
            
            #line default
            #line hidden
            return;
            case 45:
            this.ChartHostPanel = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 46:
            this.TabControlBotTab = ((System.Windows.Controls.TabControl)(target));
            return;
            case 47:
            this.GridChartControlPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 48:
            this.ButtonHideInformPanel = ((System.Windows.Controls.Button)(target));
            
            #line 131 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonHideInformPanel.Click += new System.Windows.RoutedEventHandler(this.ButtonHideInformPanel_Click);
            
            #line default
            #line hidden
            return;
            case 49:
            this.ButtonHideShowSettingsPanel = ((System.Windows.Controls.Button)(target));
            
            #line 141 "..\..\..\..\OsTrader\Panels\BotPanelChartUI.xaml"
            this.ButtonHideShowSettingsPanel.Click += new System.Windows.RoutedEventHandler(this.ButtonHideShowSettingsPanel_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

