#pragma checksum "..\..\..\OsData\OsDataUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "DFE468311FF78BF540B11AA05619F68A0CDB4466B37DBB050CA6E44171423076"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using OsEngine.OsData;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.OsData {
    
    
    /// <summary>
    /// OsDataUi
    /// </summary>
    public partial class OsDataUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 9 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridPrime;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label4;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostSource;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label24;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostSet;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button NewDataSetButton;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GreedChartPanel;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle RectChart;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost ChartHostPanel;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSetName;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSetNameValue;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelStartTimeStr;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeStartValue;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeEndStr;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar ProgressBarLoadProgress;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelTimeEndValue;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GreedLog;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControlPrime;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem Label26;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostLog;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\OsData\OsDataUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelOsa;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/osdata/osdataui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\OsData\OsDataUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.GridPrime = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.Label4 = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.HostSource = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 4:
            this.Label24 = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.HostSet = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 6:
            this.NewDataSetButton = ((System.Windows.Controls.Button)(target));
            
            #line 21 "..\..\..\OsData\OsDataUi.xaml"
            this.NewDataSetButton.Click += new System.Windows.RoutedEventHandler(this.NewDataSetButton_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.GreedChartPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 8:
            this.RectChart = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 9:
            this.ChartHostPanel = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 10:
            this.LabelSetName = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.LabelSetNameValue = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.LabelStartTimeStr = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.LabelTimeStartValue = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.LabelTimeEndStr = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.ProgressBarLoadProgress = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 16:
            this.LabelTimeEndValue = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.GreedLog = ((System.Windows.Controls.Grid)(target));
            return;
            case 18:
            this.TabControlPrime = ((System.Windows.Controls.TabControl)(target));
            return;
            case 19:
            this.Label26 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 20:
            this.HostLog = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 21:
            this.LabelOsa = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

