#pragma checksum "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "8BB5ED1C926C11908E2B2F7EF4DDA210F0D365A36582E48524490D69454AC9FE"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using OsEngine.Robots.MarketMaker;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.Robots.MarketMaker {
    
    
    /// <summary>
    /// PairTraderSimpleUi
    /// </summary>
    public partial class PairTraderSimpleUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 11 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSlippage1;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxSlipage1;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonAccept;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxCandleCount;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCandlesCount;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxRegime;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelRegime;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelVolume1;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxVolume1;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxDivergention;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSpreadExpansion;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSlippage2;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxSlipage2;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelVolume2;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxVolume2;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelProfit;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxProfit1;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelLoss;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxLoss1;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonAbout;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/robots/marketmaker/pairtradersimpleui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.LabelSlippage1 = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.TextBoxSlipage1 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.ButtonAccept = ((System.Windows.Controls.Button)(target));
            
            #line 13 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
            this.ButtonAccept.Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.TextBoxCandleCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.LabelCandlesCount = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.ComboBoxRegime = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.LabelRegime = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.LabelVolume1 = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.TextBoxVolume1 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.TextBoxDivergention = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.LabelSpreadExpansion = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.LabelSlippage2 = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.TextBoxSlipage2 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.LabelVolume2 = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.TextBoxVolume2 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.LabelProfit = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.TextBoxProfit1 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.LabelLoss = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.TextBoxLoss1 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.ButtonAbout = ((System.Windows.Controls.Button)(target));
            
            #line 31 "..\..\..\..\Robots\MarketMaker\PairTraderSimpleUi.xaml"
            this.ButtonAbout.Click += new System.Windows.RoutedEventHandler(this.ButtonAbout_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

