#pragma checksum "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "DCC0D5B4EDC9176AFAEAC71389833BD71E5D935F47DF6388B7D52922F6F0DEF8"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using OsEngine.OsTrader.Panels.Tab;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.OsTrader.Panels.Tab {
    
    
    /// <summary>
    /// BotTabPoligonSecurityAddUi
    /// </summary>
    public partial class BotTabPoligonSecurityAddUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label1;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxTypeServer;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label3;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxPortfolio;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label6;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxClass;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxIsEmulator;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonAccept;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label2;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label5;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelComissionType;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxComissionType;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelComissionValue;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxComissionValue;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost SecurityTable;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxSearchSecurity;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRightInSearchResults;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonLeftInSearchResults;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCurrentResultShow;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCommasResultShow;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCountResultsShow;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelBaseCurrency;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxBaseCurrency;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelOperation;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxOperationType;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/ostrader/panels/tab/bottabpoligonsecurityaddui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Label1 = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.ComboBoxTypeServer = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 3:
            this.Label3 = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.ComboBoxPortfolio = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.Label6 = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.ComboBoxClass = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.CheckBoxIsEmulator = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 8:
            this.ButtonAccept = ((System.Windows.Controls.Button)(target));
            
            #line 24 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPoligonSecurityAddUi.xaml"
            this.ButtonAccept.Click += new System.Windows.RoutedEventHandler(this.ButtonAccept_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.Label2 = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.Label5 = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.LabelComissionType = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.ComboBoxComissionType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 13:
            this.LabelComissionValue = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.TextBoxComissionValue = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.SecurityTable = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 16:
            this.TextBoxSearchSecurity = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.ButtonRightInSearchResults = ((System.Windows.Controls.Button)(target));
            return;
            case 18:
            this.ButtonLeftInSearchResults = ((System.Windows.Controls.Button)(target));
            return;
            case 19:
            this.LabelCurrentResultShow = ((System.Windows.Controls.Label)(target));
            return;
            case 20:
            this.LabelCommasResultShow = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.LabelCountResultsShow = ((System.Windows.Controls.Label)(target));
            return;
            case 22:
            this.LabelBaseCurrency = ((System.Windows.Controls.Label)(target));
            return;
            case 23:
            this.TextBoxBaseCurrency = ((System.Windows.Controls.TextBox)(target));
            return;
            case 24:
            this.LabelOperation = ((System.Windows.Controls.Label)(target));
            return;
            case 25:
            this.ComboBoxOperationType = ((System.Windows.Controls.ComboBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

