#pragma checksum "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "B5449C89635C8FAC890F67321ED39C105C217B1BBACB74D82EAF14A88F4255B5"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using OsEngine.OsTrader.Panels.Tab;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.OsTrader.Panels.Tab {
    
    
    /// <summary>
    /// BotTabPolygonAutoSelectSequenceUi
    /// </summary>
    public partial class BotTabPolygonAutoSelectSequenceUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 19 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label1;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxTypeServer;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Label3;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxPortfolio;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelFirstStepSecurities;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost SecuritiesHost;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonCreateSelectedSequence;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxSelectAllCheckBox;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxSearchSecurity;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSecondStep;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRightInSearchResults;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonLeftInSearchResults;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCurrentResultShow;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCommasResultShow;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelCountResultsShow;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelFinalSequence;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonCreateTableFinal;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostFirdStep;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxBaseCurrency;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelBaseCurrency;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxSeparatorToSecurities;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelSeparator;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost SecuritiesSecondStep;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxSelectAllInSecondStep;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonCreateTableSecondStep;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxSelectAllInFinalStep;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/ostrader/panels/tab/bottabpolygonautoselectsequenceui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\OsTrader\Panels\Tab\BotTabPolygonAutoSelectSequenceUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Label1 = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.ComboBoxTypeServer = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 3:
            this.Label3 = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.ComboBoxPortfolio = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.LabelFirstStepSecurities = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.SecuritiesHost = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 7:
            this.ButtonCreateSelectedSequence = ((System.Windows.Controls.Button)(target));
            return;
            case 8:
            this.CheckBoxSelectAllCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 9:
            this.TextBoxSearchSecurity = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.LabelSecondStep = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.ButtonRightInSearchResults = ((System.Windows.Controls.Button)(target));
            return;
            case 12:
            this.ButtonLeftInSearchResults = ((System.Windows.Controls.Button)(target));
            return;
            case 13:
            this.LabelCurrentResultShow = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.LabelCommasResultShow = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.LabelCountResultsShow = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.LabelFinalSequence = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.ButtonCreateTableFinal = ((System.Windows.Controls.Button)(target));
            return;
            case 18:
            this.HostFirdStep = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 19:
            this.TextBoxBaseCurrency = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.LabelBaseCurrency = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.TextBoxSeparatorToSecurities = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.LabelSeparator = ((System.Windows.Controls.Label)(target));
            return;
            case 23:
            this.SecuritiesSecondStep = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 24:
            this.CheckBoxSelectAllInSecondStep = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 25:
            this.ButtonCreateTableSecondStep = ((System.Windows.Controls.Button)(target));
            return;
            case 26:
            this.CheckBoxSelectAllInFinalStep = ((System.Windows.Controls.CheckBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

