#pragma checksum "..\..\..\..\Market\SupportTable\SupportTableUi.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "3DDB033169146D3D82ADE586606D4512C0536DDF85A4A3190B17F4E9FE4D4AE7"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using OsEngine.Market.SupportTable;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OsEngine.Market.SupportTable {
    
    
    /// <summary>
    /// SupportTableUi
    /// </summary>
    public partial class SupportTableUi : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 11 "..\..\..\..\Market\SupportTable\SupportTableUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItem1;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\..\Market\SupportTable\SupportTableUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostMoexConnections;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\Market\SupportTable\SupportTableUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItem2;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\Market\SupportTable\SupportTableUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostCryptoConnections;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\Market\SupportTable\SupportTableUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItem3;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\Market\SupportTable\SupportTableUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Forms.Integration.WindowsFormsHost HostInternationalConnections;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\Market\SupportTable\SupportTableUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabItem4;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\Market\SupportTable\SupportTableUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelPrimeSup;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\Market\SupportTable\SupportTableUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelStandartSup;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\Market\SupportTable\SupportTableUi.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelNoSup;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OsEngine;component/market/supporttable/supporttableui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Market\SupportTable\SupportTableUi.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TabItem1 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 2:
            this.HostMoexConnections = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 3:
            this.TabItem2 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 4:
            this.HostCryptoConnections = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 5:
            this.TabItem3 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 6:
            this.HostInternationalConnections = ((System.Windows.Forms.Integration.WindowsFormsHost)(target));
            return;
            case 7:
            this.TabItem4 = ((System.Windows.Controls.TabItem)(target));
            return;
            case 8:
            this.LabelPrimeSup = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.LabelStandartSup = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.LabelNoSup = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

